<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rubén Rodríguez Fernández">
<meta name="author" content="Víctor Aceña Gil">

<title>Sesión 2. Transformar y visualizar datos – Curso de iniciación a R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ff63373b1067ca6f91cf1456aa1f00a2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/kbd/kbd.js"></script>
<link href="site_libs/quarto-contrib/kbd/kbd.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Curso de iniciación a R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./00_preparacion/preparacion.html"> 
<span class="menu-text">Preparación</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sesión-1" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Sesión 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sesión-1">    
        <li>
    <a class="dropdown-item" href="./sesion1.html">
 <span class="dropdown-text">Apuntes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sesion1_ejercicios.html">
 <span class="dropdown-text">Ejercicios</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./informe_ejemplo.html">
 <span class="dropdown-text">Ejemplo de informe</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sesión-2" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Sesión 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sesión-2">    
        <li>
    <a class="dropdown-item" href="./sesion2.html">
 <span class="dropdown-text">Apuntes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sesion2_ejercicios.html">
 <span class="dropdown-text">Ejercicios</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul class="collapse">
  <li><a href="#bloque-2-1" id="toc-bloque-2-1" class="nav-link active" data-scroll-target="#bloque-2-1">2.1. Transformar datos con <code>dplyr</code></a>
  <ul class="collapse">
  <li><a href="#el-tidyverse-y-la-tubería" id="toc-el-tidyverse-y-la-tubería" class="nav-link" data-scroll-target="#el-tidyverse-y-la-tubería">El <em>tidyverse</em> y la “tubería” <code>|&gt;</code></a></li>
  <li><a href="#operaciones-con-filas" id="toc-operaciones-con-filas" class="nav-link" data-scroll-target="#operaciones-con-filas">Operaciones con filas</a></li>
  <li><a href="#operaciones-con-columnas" id="toc-operaciones-con-columnas" class="nav-link" data-scroll-target="#operaciones-con-columnas">Operaciones con columnas</a></li>
  <li><a href="#resumir-datos" id="toc-resumir-datos" class="nav-link" data-scroll-target="#resumir-datos">Resumir datos</a></li>
  <li><a href="#resumir-por-grupos" id="toc-resumir-por-grupos" class="nav-link" data-scroll-target="#resumir-por-grupos">Resumir por grupos</a></li>
  <li><a href="#la-limpieza-de-la-sesión-1-con-dplyr" id="toc-la-limpieza-de-la-sesión-1-con-dplyr" class="nav-link" data-scroll-target="#la-limpieza-de-la-sesión-1-con-dplyr">La limpieza de la sesión 1, con <code>dplyr</code></a></li>
  </ul></li>
  <li><a href="#bloque-2-2" id="toc-bloque-2-2" class="nav-link" data-scroll-target="#bloque-2-2">2.2. Recodificar, puntuar y resumir</a>
  <ul class="collapse">
  <li><a href="#recodificar-if_else-y-case_when" id="toc-recodificar-if_else-y-case_when" class="nav-link" data-scroll-target="#recodificar-if_else-y-case_when">Recodificar: <code>if_else()</code> y <code>case_when()</code></a></li>
  <li><a href="#la-puntuación-de-cada-escala" id="toc-la-puntuación-de-cada-escala" class="nav-link" data-scroll-target="#la-puntuación-de-cada-escala">La puntuación de cada escala</a></li>
  <li><a href="#resumir-varias-variables-a-la-vez-across" id="toc-resumir-varias-variables-a-la-vez-across" class="nav-link" data-scroll-target="#resumir-varias-variables-a-la-vez-across">Resumir varias variables a la vez: <code>across()</code></a></li>
  <li><a href="#seleccionar-filas-por-posición-slice_" id="toc-seleccionar-filas-por-posición-slice_" class="nav-link" data-scroll-target="#seleccionar-filas-por-posición-slice_">Seleccionar filas por posición: <code>slice_*()</code></a></li>
  <li><a href="#mutate-por-grupos" id="toc-mutate-por-grupos" class="nav-link" data-scroll-target="#mutate-por-grupos"><code>mutate()</code> por grupos</a></li>
  </ul></li>
  <li><a href="#ejercicio-1" id="toc-ejercicio-1" class="nav-link" data-scroll-target="#ejercicio-1">Ejercicio 1</a></li>
  <li><a href="#bloque-2-3" id="toc-bloque-2-3" class="nav-link" data-scroll-target="#bloque-2-3">2.3. Reorganizar y combinar tablas</a>
  <ul class="collapse">
  <li><a href="#datos-ordenados-tidy-data" id="toc-datos-ordenados-tidy-data" class="nav-link" data-scroll-target="#datos-ordenados-tidy-data">Datos ordenados (<em>tidy data</em>)</a></li>
  <li><a href="#de-ancho-a-largo-pivot_longer" id="toc-de-ancho-a-largo-pivot_longer" class="nav-link" data-scroll-target="#de-ancho-a-largo-pivot_longer">De ancho a largo: <code>pivot_longer()</code></a></li>
  <li><a href="#de-largo-a-ancho-pivot_wider" id="toc-de-largo-a-ancho-pivot_wider" class="nav-link" data-scroll-target="#de-largo-a-ancho-pivot_wider">De largo a ancho: <code>pivot_wider()</code></a></li>
  <li><a href="#combinar-tablas-joins" id="toc-combinar-tablas-joins" class="nav-link" data-scroll-target="#combinar-tablas-joins">Combinar tablas: <em>joins</em></a></li>
  </ul></li>
  <li><a href="#bloque-2-4" id="toc-bloque-2-4" class="nav-link" data-scroll-target="#bloque-2-4">2.4. Gráficos con <code>ggplot2</code></a>
  <ul class="collapse">
  <li><a href="#la-gramática-de-los-gráficos" id="toc-la-gramática-de-los-gráficos" class="nav-link" data-scroll-target="#la-gramática-de-los-gráficos">La gramática de los gráficos</a></li>
  <li><a href="#asignar-o-fijar-dentro-o-fuera-de-aes" id="toc-asignar-o-fijar-dentro-o-fuera-de-aes" class="nav-link" data-scroll-target="#asignar-o-fijar-dentro-o-fuera-de-aes">Asignar o fijar: dentro o fuera de <code>aes()</code></a></li>
  <li><a href="#distribución-de-una-variable" id="toc-distribución-de-una-variable" class="nav-link" data-scroll-target="#distribución-de-una-variable">Distribución de una variable</a></li>
  <li><a href="#comparar-grupos-diagramas-de-caja" id="toc-comparar-grupos-diagramas-de-caja" class="nav-link" data-scroll-target="#comparar-grupos-diagramas-de-caja">Comparar grupos: diagramas de caja</a></li>
  <li><a href="#frecuencias-gráficos-de-barras" id="toc-frecuencias-gráficos-de-barras" class="nav-link" data-scroll-target="#frecuencias-gráficos-de-barras">Frecuencias: gráficos de barras</a></li>
  <li><a href="#paneles-facet_wrap" id="toc-paneles-facet_wrap" class="nav-link" data-scroll-target="#paneles-facet_wrap">Paneles: <code>facet_wrap()</code></a></li>
  <li><a href="#medias-por-grupo-y-momento-el-gráfico-de-una-intervención" id="toc-medias-por-grupo-y-momento-el-gráfico-de-una-intervención" class="nav-link" data-scroll-target="#medias-por-grupo-y-momento-el-gráfico-de-una-intervención">Medias por grupo y momento: el gráfico de una intervención</a></li>
  <li><a href="#ajustar-el-aspecto" id="toc-ajustar-el-aspecto" class="nav-link" data-scroll-target="#ajustar-el-aspecto">Ajustar el aspecto</a></li>
  <li><a href="#guardar-un-gráfico" id="toc-guardar-un-gráfico" class="nav-link" data-scroll-target="#guardar-un-gráfico">Guardar un gráfico</a></li>
  </ul></li>
  <li><a href="#bloque-2-5" id="toc-bloque-2-5" class="nav-link" data-scroll-target="#bloque-2-5">2.5. Primeros análisis</a>
  <ul class="collapse">
  <li><a href="#correlación" id="toc-correlación" class="nav-link" data-scroll-target="#correlación">Correlación</a></li>
  <li><a href="#prueba-t" id="toc-prueba-t" class="nav-link" data-scroll-target="#prueba-t">Prueba <em>t</em></a></li>
  <li><a href="#regresión-lineal" id="toc-regresión-lineal" class="nav-link" data-scroll-target="#regresión-lineal">Regresión lineal</a></li>
  <li><a href="#los-resultados-son-listas" id="toc-los-resultados-son-listas" class="nav-link" data-scroll-target="#los-resultados-son-listas">Los resultados son listas</a></li>
  </ul></li>
  <li><a href="#bloque-2-6" id="toc-bloque-2-6" class="nav-link" data-scroll-target="#bloque-2-6">2.6. Resultados en Quarto y tu propio proyecto con <code>renv</code></a>
  <ul class="collapse">
  <li><a href="#un-informe-con-resultados" id="toc-un-informe-con-resultados" class="nav-link" data-scroll-target="#un-informe-con-resultados">Un informe con resultados</a></li>
  <li><a href="#tu-propio-proyecto-con-renv" id="toc-tu-propio-proyecto-con-renv" class="nav-link" data-scroll-target="#tu-propio-proyecto-con-renv">Tu propio proyecto con <code>renv</code></a></li>
  </ul></li>
  <li><a href="#ejercicio-2" id="toc-ejercicio-2" class="nav-link" data-scroll-target="#ejercicio-2">Ejercicio 2</a>
  <ul class="collapse">
  <li><a href="#para-seguir-aprendiendo" id="toc-para-seguir-aprendiendo" class="nav-link" data-scroll-target="#para-seguir-aprendiendo">Para seguir aprendiendo</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sesión 2. Transformar y visualizar datos</h1>
<p class="subtitle lead">Curso de iniciación a R. Departamento de Ciencias de la Educación, Universidad de Alcalá</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autores/as</div>
  <div class="quarto-title-meta-heading">Afiliación</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Rubén Rodríguez Fernández <a href="mailto:ruben.rodriguez@urjc.es" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Rey Juan Carlos
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Víctor Aceña Gil <a href="mailto:victor.acena@urjc.es" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Rey Juan Carlos
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<!-- Las soluciones están ocultas. Para verlas: quarto render sesionX.qmd -M solucion:true -->
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bloque</th>
<th>Contenido</th>
<th>Tiempo aprox.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2.1</td>
<td>Transformar datos con <code>dplyr</code></td>
<td>40 min</td>
</tr>
<tr class="even">
<td>2.2</td>
<td>Recodificar, puntuar y resumir</td>
<td>25 min</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>Ejercicio 1</strong> y puesta en común</td>
<td>25 min</td>
</tr>
<tr class="even">
<td></td>
<td><em>Descanso</em></td>
<td>15 min</td>
</tr>
<tr class="odd">
<td>2.3</td>
<td>Reorganizar y combinar tablas</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>2.4</td>
<td>Gráficos con <code>ggplot2</code></td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>2.5</td>
<td>Primeros análisis</td>
<td>20 min</td>
</tr>
<tr class="even">
<td>2.6</td>
<td>Resultados en Quarto y tu propio proyecto con <code>renv</code></td>
<td>15 min</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>Ejercicio 2</strong> y puesta en común</td>
<td>25 min</td>
</tr>
</tbody>
</table>
<p>Recuerda: los ejercicios están en <code>sesion2_ejercicios.qmd</code>.</p>
<p>Partimos de los datos que limpiamos en la sesión 1:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>encuesta <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"checkpoints/encuesta_limpia.rds"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="bloque-2-1" class="level1">
<h1>2.1. Transformar datos con <code>dplyr</code></h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seleccionar, filtrar, ordenar, crear variables y resumir datos por grupos: las operaciones que harás en todos tus análisis.</p>
<p><strong>Punto de control:</strong> <code>encuesta &lt;- readRDS("checkpoints/encuesta_limpia.rds")</code></p>
</div>
</div>
<section id="el-tidyverse-y-la-tubería" class="level2">
<h2 class="anchored" data-anchor-id="el-tidyverse-y-la-tubería">El <em>tidyverse</em> y la “tubería” <code>|&gt;</code></h2>
<p>El <em>tidyverse</em> es un conjunto de paquetes diseñados para el análisis de datos que comparten una misma filosofía y “gramática”: <code>readr</code> (importar ficheros de texto), <code>tibble</code> (tablas), <code>dplyr</code> (transformar), <code>tidyr</code> (reorganizar), <code>ggplot2</code> (gráficos), entre otros. Con <code>library(tidyverse)</code> se cargan todos.</p>
<p>El paquete central para transformar datos es <code>dplyr</code>, que ofrece un conjunto de <strong>verbos</strong> (funciones) con nombres que dicen lo que hacen. Todos reciben una tabla como primer argumento y devuelven otra tabla.</p>
<p>Por eso se pueden encadenar con el operador <code>|&gt;</code> (<em>pipe</em> o tubería, atajo <kbd title="Ctrl+Shift+M" aria-hidden="true">Ctrl+Shift+M</kbd><span class="visually-hidden">Ctrl+Shift+M</span>): el resultado de la izquierda pasa como primer argumento a la función de la derecha. Es decir, <code>x |&gt; f()</code> es lo mismo que <code>f(x)</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>notas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">6.5</span>, <span class="fl">8.0</span>, <span class="fl">4.5</span>, <span class="fl">9.2</span>, <span class="fl">5.0</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(notas), <span class="dv">1</span>)          <span class="co"># se lee de dentro afuera</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>notas <span class="sc">|&gt;</span> <span class="fu">mean</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">1</span>)    <span class="co"># se lee de izquierda a derecha</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.6</code></pre>
</div>
</div>
<p>La tubería se lee como <strong>“y después”</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span>              <span class="co"># toma la encuesta, y después</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(...) <span class="sc">|&gt;</span>         <span class="co"># quédate con algunas filas, y después</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(...) <span class="sc">|&gt;</span>         <span class="co"># quédate con algunas columnas, y después</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(...)         <span class="co"># resume</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Dentro de los verbos de <code>dplyr</code>, las columnas se escriben <strong>sin</strong> <code>encuesta$</code> y sin comillas: el verbo ya sabe en qué tabla buscarlas.</p>
<p>Los verbos no modifican la tabla original: devuelven una nueva. Si queremos guardar el resultado, lo asignamos a un nombre:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> encuesta <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(...)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="operaciones-con-filas" class="level2">
<h2 class="anchored" data-anchor-id="operaciones-con-filas">Operaciones con filas</h2>
<p><strong>Filtrar</strong> filas que cumplen una condición, con <code>filter()</code>. Se usan las comparaciones de la sesión 1:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(curso <span class="sc">==</span> <span class="st">"1º ESO"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 78 × 19
   marca_temporal   id    centro curso sexo   edad    m1    m2    m3    m4    a1
   &lt;chr&gt;            &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 05/10/2026 10:2… E001  C08    1º E… Chico    13     2     1     2     4     4
 2 05/10/2026 13:5… E002  C03    1º E… Chico    13     4     3     3     2     4
 3 05/10/2026 19:0… E009  C07    1º E… Chico    13     4     4     4     2    NA
 4 05/10/2026 19:4… E010  C03    1º E… Chica    12     5     5     5     2     5
 5 06/10/2026 02:0… E015  C02    1º E… Chica    13     3     3     4     3     3
 6 06/10/2026 06:2… E020  C02    1º E… Pref…    12     2     4     2     5     4
 7 06/10/2026 08:4… E024  C02    1º E… Chica    12     3     4     4     1     1
 8 07/10/2026 04:2… E039  C05    1º E… Chico    12     4     3     3     3     2
 9 07/10/2026 05:3… E040  C01    1º E… Pref…    12     5     5     5     1     3
10 07/10/2026 08:2… E043  C01    1º E… Chico    13     4     4     3     2     4
# ℹ 68 more rows
# ℹ 8 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Varias condiciones separadas por comas deben cumplirse todas (equivale a <code>&amp;</code>). Para “una u otra”, <code>|</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(curso <span class="sc">==</span> <span class="st">"4º ESO"</span>, nota <span class="sc">&lt;</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 19
   marca_temporal   id    centro curso sexo   edad    m1    m2    m3    m4    a1
   &lt;chr&gt;            &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 06/10/2026 05:2… E019  C07    4º E… Chico    15     2     2     1     5     2
 2 06/10/2026 10:4… E026  C02    4º E… Chica    15     3     2     3     4     3
 3 06/10/2026 21:1… E035  C03    4º E… Chica    16     2     3     3     3     4
 4 07/10/2026 00:4… E037  C07    4º E… Chico    15     2     1     1     5     4
 5 08/10/2026 06:1… E067  C08    4º E… Chica    15     3     2     3     4     5
 6 08/10/2026 22:4… E089  C07    4º E… Chico    15    NA     2     2     5     1
 7 09/10/2026 02:5… E094  C07    4º E… Chica    15     2     3     3     4     4
 8 10/10/2026 10:2… E117  C03    4º E… Chica    16     2     2     2     5     5
 9 11/10/2026 13:2… E144  C08    4º E… Chica    15     4     4     4     2     3
10 11/10/2026 21:4… E155  C05    4º E… Chica    16     1     1     2     4     2
11 12/10/2026 01:3… E161  C02    4º E… Chico    15     1     1     1    NA     4
12 13/10/2026 03:0… E190  C01    4º E… Chica    15     1     1     2     5     4
13 13/10/2026 15:1… E194  C09    4º E… Chico    15     3     4     2     2     3
14 14/10/2026 18:2… E219  C02    4º E… Chica    15     2     2     2     5     4
15 15/10/2026 04:5… E229  C07    4º E… Chico    15     1     1     2     5     4
16 17/10/2026 15:3… E278  C08    4º E… Chica    16     2    NA     2     5     2
17 19/10/2026 07:1… E319  C08    4º E… Chica    15     3     3     4     4     5
# ℹ 8 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nota <span class="sc">&gt;=</span> <span class="fl">9.5</span> <span class="sc">|</span> nota <span class="sc">&lt;</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 19
   marca_temporal   id    centro curso sexo   edad    m1    m2    m3    m4    a1
   &lt;chr&gt;            &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 05/10/2026 19:4… E010  C03    1º E… Chica    12     5     5     5     2     5
 2 05/10/2026 23:4… E013  C07    2º E… Chico    14     3     3     5     2    NA
 3 06/10/2026 21:1… E036  C01    2º E… Chico    13     1     2     1     5     4
 4 08/10/2026 00:5… E060  C07    3º E… Chica    14     1     1     1     4     5
 5 08/10/2026 01:3… E062  C09    3º E… Chica    14     5     4     5     2     2
 6 08/10/2026 18:0… E082  C06    3º E… Chica    14     4    NA     5     2     2
 7 09/10/2026 02:5… E095  C07    2º E… Chico    14     4     4     4     3     2
 8 11/10/2026 23:2… E157  C01    2º E… Chico    13     1    NA     2     4     3
 9 12/10/2026 01:3… E161  C02    4º E… Chico    15     1     1     1    NA     4
10 12/10/2026 03:3… E167  C02    1º E… Chica    12     4     5     4     1     1
11 13/10/2026 23:0… E200  C02    1º E… Chico    12     5     3     5     1     2
12 15/10/2026 16:4… E238  C02    1º E… Chico    13     4     4     5     2     2
13 16/10/2026 20:1… E262  C03    2º E… Chico    13     4     4     4     4     3
14 17/10/2026 12:1… E274  C07    1º E… Chica    13     5     5     4     1     3
15 19/10/2026 01:4… E313  C07    1º E… Chico    12     5     5     5     1     2
# ℹ 8 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Para comprobar si un valor está en un conjunto, <code>%in%</code>; para quitar los casos sin nota, <code>!is.na()</code> (“que <strong>no</strong> sea <code>NA</code>”):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(centro <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"C01"</span>, <span class="st">"C02"</span>, <span class="st">"C03"</span>), <span class="sc">!</span><span class="fu">is.na</span>(nota))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 156 × 19
   marca_temporal   id    centro curso sexo   edad    m1    m2    m3    m4    a1
   &lt;chr&gt;            &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 05/10/2026 13:5… E002  C03    1º E… Chico    13     4     3     3     2     4
 2 05/10/2026 13:5… E003  C02    2º E… Chico    14    NA     2     3     3     4
 3 05/10/2026 14:5… E005  C03    3º E… Chica    14     3     3    NA     2     3
 4 05/10/2026 16:0… E006  C02    3º E… Chico    15     3     3     3     5     3
 5 05/10/2026 18:0… E007  C01    4º E… Chico    15     5     4     4     1     3
 6 05/10/2026 19:4… E010  C03    1º E… Chica    12     5     5     5     2     5
 7 05/10/2026 20:2… E011  C02    3º E… Chico    15     3     4     3     4     3
 8 06/10/2026 02:0… E015  C02    1º E… Chica    13     3     3     4     3     3
 9 06/10/2026 04:2… E017  C03    2º E… Chico    13     3     4     2     2     3
10 06/10/2026 05:0… E018  C02    4º E… Chico    16     3     3     4     2     5
# ℹ 146 more rows
# ℹ 8 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Ordenar</strong> con <code>arrange()</code>; para orden descendente, <code>desc()</code>. Con varias columnas, se ordena por la primera y, en caso de empate, por la siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(curso, <span class="fu">desc</span>(nota))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 19
   marca_temporal   id    centro curso sexo   edad    m1    m2    m3    m4    a1
   &lt;chr&gt;            &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 13/10/2026 23:0… E200  C02    1º E… Chico    12     5     3     5     1     2
 2 17/10/2026 12:1… E274  C07    1º E… Chica    13     5     5     4     1     3
 3 19/10/2026 01:4… E313  C07    1º E… Chico    12     5     5     5     1     2
 4 15/10/2026 16:4… E238  C02    1º E… Chico    13     4     4     5     2     2
 5 12/10/2026 03:3… E167  C02    1º E… Chica    12     4     5     4     1     1
 6 05/10/2026 19:4… E010  C03    1º E… Chica    12     5     5     5     2     5
 7 14/10/2026 11:4… E212  C02    1º E… Chica    13     4     4     4     3     2
 8 09/10/2026 05:0… E096  C07    1º E… Chico    12     4     4     5     3     2
 9 10/10/2026 16:0… E125  C01    1º E… Chica    13     4     3    NA     4    NA
10 06/10/2026 02:0… E015  C02    1º E… Chica    13     3     3     4     3     3
# ℹ 310 more rows
# ℹ 8 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Quitar duplicados</strong> con <code>distinct()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(centro, curso)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 38 × 2
   centro curso 
   &lt;fct&gt;  &lt;fct&gt; 
 1 C08    1º ESO
 2 C03    1º ESO
 3 C02    2º ESO
 4 C07    2º ESO
 5 C03    3º ESO
 6 C02    3º ESO
 7 C01    4º ESO
 8 C04    4º ESO
 9 C07    1º ESO
10 C08    3º ESO
# ℹ 28 more rows</code></pre>
</div>
</div>
</section>
<section id="operaciones-con-columnas" class="level2">
<h2 class="anchored" data-anchor-id="operaciones-con-columnas">Operaciones con columnas</h2>
<p><strong>Seleccionar</strong> columnas con <code>select()</code>: por su nombre, por rango (<code>m1:m4</code>) o con funciones auxiliares. Un signo menos elimina columnas:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, curso, sexo, nota)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 4
   id    curso  sexo   nota
   &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;dbl&gt;
 1 E001  1º ESO Chico   5.5
 2 E002  1º ESO Chico   4.1
 3 E003  2º ESO Chico   7.7
 4 E004  2º ESO Chico   4.8
 5 E005  3º ESO Chica   7.5
 6 E006  3º ESO Chico   8.1
 7 E007  4º ESO Chico   6.8
 8 E008  4º ESO Chico   7.8
 9 E009  1º ESO Chico   6.8
10 E010  1º ESO Chica   9.6
# ℹ 310 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, m1<span class="sc">:</span>m4)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 5
   id       m1    m2    m3    m4
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 E001      2     1     2     4
 2 E002      4     3     3     2
 3 E003     NA     2     3     3
 4 E004      4     3     4     2
 5 E005      3     3    NA     2
 6 E006      3     3     3     5
 7 E007      5     4     4     1
 8 E008      5     5     2     3
 9 E009      4     4     4     2
10 E010      5     5     5     2
# ℹ 310 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>marca_temporal)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 18
   id    centro curso  sexo   edad    m1    m2    m3    m4    a1    a2    a3
   &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 E001  C08    1º ESO Chico    13     2     1     2     4     4     4     3
 2 E002  C03    1º ESO Chico    13     4     3     3     2     4     5     3
 3 E003  C02    2º ESO Chico    14    NA     2     3     3     4     4     4
 4 E004  C07    2º ESO Chico    13     4     3     4     2     5     5     3
 5 E005  C03    3º ESO Chica    14     3     3    NA     2     3     2     4
 6 E006  C02    3º ESO Chico    15     3     3     3     5     3     4     2
 7 E007  C01    4º ESO Chico    15     5     4     4     1     3     4     3
 8 E008  C04    4º ESO Chico    15     5     5     2     3     3     3     3
 9 E009  C07    1º ESO Chico    13     4     4     4     2    NA     5     4
10 E010  C03    1º ESO Chica    12     5     5     5     2     5     4     3
# ℹ 310 more rows
# ℹ 6 more variables: a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;, ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;,
#   nota &lt;dbl&gt;</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Función auxiliar</th>
<th>Selecciona las columnas que…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>starts_with("ae")</code></td>
<td>empiezan por <code>ae</code></td>
</tr>
<tr class="even">
<td><code>ends_with("_pre")</code></td>
<td>terminan en <code>_pre</code></td>
</tr>
<tr class="odd">
<td><code>contains("nota")</code></td>
<td>contienen <code>nota</code></td>
</tr>
<tr class="even">
<td><code>where(is.numeric)</code></td>
<td>son numéricas (o <code>is.factor</code>, <code>is.character</code>…)</td>
</tr>
<tr class="odd">
<td><code>everything()</code></td>
<td>todas las demás</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, <span class="fu">starts_with</span>(<span class="st">"ae"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 5
   id      ae1   ae2   ae3   ae4
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 E001      3     3     4     2
 2 E002      3     3     2     3
 3 E003      2     2     4     2
 4 E004      3     3     4     4
 5 E005      4     4     2     3
 6 E006      2     3     3     4
 7 E007      2     4     3     5
 8 E008      3     2     3     4
 9 E009      4     2     3     2
10 E010      4     5     1     5
# ℹ 310 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.factor))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 3
   centro curso  sexo 
   &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt;
 1 C08    1º ESO Chico
 2 C03    1º ESO Chico
 3 C02    2º ESO Chico
 4 C07    2º ESO Chico
 5 C03    3º ESO Chica
 6 C02    3º ESO Chico
 7 C01    4º ESO Chico
 8 C04    4º ESO Chico
 9 C07    1º ESO Chico
10 C03    1º ESO Chica
# ℹ 310 more rows</code></pre>
</div>
</div>
<p><strong>Cambiar nombres</strong> con <code>rename(nuevo = antiguo)</code>, y <strong>cambiar el orden</strong> de las columnas con <code>relocate()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">nota_1ev =</span> nota) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(nota_1ev, <span class="at">.after =</span> id)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 19
   marca_temporal      id    nota_1ev centro curso sexo   edad    m1    m2    m3
   &lt;chr&gt;               &lt;chr&gt;    &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 05/10/2026 10:28:58 E001       5.5 C08    1º E… Chico    13     2     1     2
 2 05/10/2026 13:50:29 E002       4.1 C03    1º E… Chico    13     4     3     3
 3 05/10/2026 13:55:31 E003       7.7 C02    2º E… Chico    14    NA     2     3
 4 05/10/2026 14:45:14 E004       4.8 C07    2º E… Chico    13     4     3     4
 5 05/10/2026 14:50:14 E005       7.5 C03    3º E… Chica    14     3     3    NA
 6 05/10/2026 16:08:17 E006       8.1 C02    3º E… Chico    15     3     3     3
 7 05/10/2026 18:04:37 E007       6.8 C01    4º E… Chico    15     5     4     4
 8 05/10/2026 18:10:02 E008       7.8 C04    4º E… Chico    15     5     5     2
 9 05/10/2026 19:06:28 E009       6.8 C07    1º E… Chico    13     4     4     4
10 05/10/2026 19:43:15 E010       9.6 C03    1º E… Chica    12     5     5     5
# ℹ 310 more rows
# ℹ 9 more variables: m4 &lt;dbl&gt;, a1 &lt;dbl&gt;, a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;,
#   ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;, ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Crear o modificar</strong> variables con <code>mutate()</code>, con pares <code>nombre = expresión</code>. Si el nombre ya existe, la columna se sustituye:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">aprobado =</span> nota <span class="sc">&gt;=</span> <span class="dv">5</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">nota_100 =</span> nota <span class="sc">*</span> <span class="dv">10</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad =</span> edad <span class="sc">-</span> <span class="dv">12</span>          <span class="co"># años desde los 12</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, nota, aprobado, nota_100, edad)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 5
   id     nota aprobado nota_100  edad
   &lt;chr&gt; &lt;dbl&gt; &lt;lgl&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 E001    5.5 TRUE           55     1
 2 E002    4.1 FALSE          41     1
 3 E003    7.7 TRUE           77     2
 4 E004    4.8 FALSE          48     1
 5 E005    7.5 TRUE           75     2
 6 E006    8.1 TRUE           81     3
 7 E007    6.8 TRUE           68     3
 8 E008    7.8 TRUE           78     3
 9 E009    6.8 TRUE           68     1
10 E010    9.6 TRUE           96     0
# ℹ 310 more rows</code></pre>
</div>
</div>
</section>
<section id="resumir-datos" class="level2">
<h2 class="anchored" data-anchor-id="resumir-datos">Resumir datos</h2>
<p><strong>Contar</strong> con <code>count()</code>. Con <code>sort = TRUE</code>, de más a menos frecuente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(centro, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   centro     n
   &lt;fct&gt;  &lt;int&gt;
 1 C02       75
 2 C01       45
 3 C07       43
 4 C08       43
 5 C03       38
 6 C05       24
 7 C09       16
 8 C04       15
 9 C06       11
10 C10       10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(curso, sexo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   curso  sexo                    n
   &lt;fct&gt;  &lt;fct&gt;               &lt;int&gt;
 1 1º ESO Chica                  39
 2 1º ESO Chico                  34
 3 1º ESO Prefiero no decirlo     5
 4 2º ESO Chica                  44
 5 2º ESO Chico                  47
 6 2º ESO Prefiero no decirlo     4
 7 3º ESO Chica                  26
 8 3º ESO Chico                  41
 9 3º ESO Prefiero no decirlo     3
10 4º ESO Chica                  37
11 4º ESO Chico                  40</code></pre>
</div>
</div>
<p><strong>Resumir</strong> con <code>summarise()</code>: cualquier función que devuelva un único valor (<code>mean</code>, <code>sd</code>, <code>median</code>, <code>min</code>, <code>max</code>…), <code>n()</code> para el número de filas y <code>n_distinct()</code> para el número de valores distintos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">centros =</span> <span class="fu">n_distinct</span>(centro),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">media_nota =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt_nota =</span> <span class="fu">sd</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">aprobados =</span> <span class="fu">mean</span>(nota <span class="sc">&gt;=</span> <span class="dv">5</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
      n centros media_nota dt_nota aprobados
  &lt;int&gt;   &lt;int&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
1   320      10       6.15    1.66      74.8</code></pre>
</div>
</div>
</section>
<section id="resumir-por-grupos" class="level2">
<h2 class="anchored" data-anchor-id="resumir-por-grupos">Resumir por grupos</h2>
<p>Lo más habitual es combinar <code>summarise()</code> con <code>group_by()</code>: el resumen se calcula para cada grupo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curso) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">media_nota =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt_nota =</span> <span class="fu">sd</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  curso      n media_nota dt_nota
  &lt;fct&gt;  &lt;int&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 1º ESO    78       6.29    1.78
2 2º ESO    95       6.14    1.73
3 3º ESO    70       6.17    1.71
4 4º ESO    77       5.99    1.40</code></pre>
</div>
</div>
<p>Se puede agrupar por varias variables. <code>.groups = "drop"</code> quita la agrupación al terminar (si no, R nos avisa de que la tabla sigue agrupada):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sexo <span class="sc">!=</span> <span class="st">"Prefiero no decirlo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curso, sexo) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">media_nota =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  curso  sexo      n media_nota
  &lt;fct&gt;  &lt;fct&gt; &lt;int&gt;      &lt;dbl&gt;
1 1º ESO Chica    39       6.24
2 1º ESO Chico    34       6.41
3 2º ESO Chica    44       6.15
4 2º ESO Chico    47       6.14
5 3º ESO Chica    26       6.03
6 3º ESO Chico    41       6.22
7 4º ESO Chica    37       5.59
8 4º ESO Chico    40       6.35</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>También con RStudio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Añade <code>|&gt; View()</code> al final de cualquier cadena para ver el resultado como hoja de cálculo. En esa vista se puede ordenar y filtrar con el ratón, pero solo para mirar: para que el filtro forme parte del análisis, escríbelo con <code>filter()</code>.</p>
</div>
</div>
</section>
<section id="la-limpieza-de-la-sesión-1-con-dplyr" class="level2">
<h2 class="anchored" data-anchor-id="la-limpieza-de-la-sesión-1-con-dplyr">La limpieza de la sesión 1, con <code>dplyr</code></h2>
<p>En la sesión 1 convertimos los 12 ítems en números con un bucle. Con <code>mutate()</code> y <code>across()</code> (“a lo largo de” varias columnas) toda la limpieza se escribe en una sola cadena. <code>across()</code> recibe las columnas y la función que hay que aplicar a cada una:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>diccionario <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"datos/encuesta_bruta.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"diccionario"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>encuesta_dplyr <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"datos/encuesta_bruta.xlsx"</span>, <span class="at">na =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"NS/NC"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(\(x) diccionario<span class="sc">$</span>codigo) <span class="sc">|&gt;</span>               <span class="co"># nombres del diccionario</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad =</span> <span class="fu">parse_number</span>(edad),</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(m1<span class="sc">:</span>ae4, parse_number),                       <span class="co"># los 12 ítems de una vez</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">centro =</span> <span class="fu">factor</span>(centro),</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">curso =</span> <span class="fu">factor</span>(curso, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1º ESO"</span>, <span class="st">"2º ESO"</span>, <span class="st">"3º ESO"</span>, <span class="st">"4º ESO"</span>)),</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sexo =</span> <span class="fu">factor</span>(sexo)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(encuesta_dplyr, encuesta)    <span class="co"># ¿el mismo resultado que en la sesión 1?</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p><code>\(x)</code> es una forma abreviada de escribir <code>function(x)</code>: una pequeña función sin nombre, como las que creamos en la sesión 1. Aquí recibe los nombres antiguos y devuelve los del diccionario.</p>
</section>
</section>
<section id="bloque-2-2" class="level1">
<h1>2.2. Recodificar, puntuar y resumir</h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recodificar variables, calcular la puntuación de cada escala y obtener resúmenes de varias variables a la vez.</p>
<p><strong>Punto de control:</strong> <code>encuesta &lt;- readRDS("checkpoints/encuesta_limpia.rds")</code></p>
<p><strong>Al final del bloque:</strong> <code>checkpoints/encuesta_escalas.rds</code></p>
</div>
</div>
<section id="recodificar-if_else-y-case_when" class="level2">
<h2 class="anchored" data-anchor-id="recodificar-if_else-y-case_when">Recodificar: <code>if_else()</code> y <code>case_when()</code></h2>
<p><code>if_else()</code> es la versión del <em>tidyverse</em> de <code>ifelse()</code>. Para varias categorías, <code>case_when()</code> evalúa las condiciones en orden y asigna el valor de la primera que se cumple (<code>condición ~ valor</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="ot">&lt;-</span> encuesta <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ciclo =</span> <span class="fu">if_else</span>(curso <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"1º ESO"</span>, <span class="st">"2º ESO"</span>), <span class="st">"Primer ciclo"</span>, <span class="st">"Segundo ciclo"</span>),</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">calificacion =</span> <span class="fu">case_when</span>(</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>      nota <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Suspenso"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>      nota <span class="sc">&lt;</span> <span class="dv">7</span> <span class="sc">~</span> <span class="st">"Aprobado"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>      nota <span class="sc">&lt;</span> <span class="dv">9</span> <span class="sc">~</span> <span class="st">"Notable"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>      nota <span class="sc">&gt;=</span> <span class="dv">9</span> <span class="sc">~</span> <span class="st">"Sobresaliente"</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">calificacion =</span> <span class="fu">factor</span>(calificacion, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Suspenso"</span>, <span class="st">"Aprobado"</span>, <span class="st">"Notable"</span>, <span class="st">"Sobresaliente"</span>))</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(ciclo, calificacion)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  ciclo         calificacion      n
  &lt;chr&gt;         &lt;fct&gt;         &lt;int&gt;
1 Primer ciclo  Suspenso         45
2 Primer ciclo  Aprobado         65
3 Primer ciclo  Notable          46
4 Primer ciclo  Sobresaliente    11
5 Primer ciclo  &lt;NA&gt;              6
6 Segundo ciclo Suspenso         34
7 Segundo ciclo Aprobado         74
8 Segundo ciclo Notable          35
9 Segundo ciclo Sobresaliente     4</code></pre>
</div>
</div>
<p>Si no se cumple ninguna condición (por ejemplo, porque la nota es <code>NA</code>), el resultado es <code>NA</code>. Con <code>.default = "valor"</code> se puede asignar otro valor a esos casos.</p>
</section>
<section id="la-puntuación-de-cada-escala" class="level2">
<h2 class="anchored" data-anchor-id="la-puntuación-de-cada-escala">La puntuación de cada escala</h2>
<p>La puntuación de cada participante en una escala suele ser la media de sus ítems. <code>rowMeans()</code> calcula medias por fila y <code>pick()</code> selecciona las columnas dentro de <code>mutate()</code>.</p>
<p>En el diccionario, <code>m4</code> y <code>ae3</code> están redactados en sentido contrario al resto de su escala (<em>“Solo estudio porque me obligan”</em>), así que antes de promediar los invertimos: en una escala de 1 a 5, <code>6 - valor</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="ot">&lt;-</span> encuesta <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">m4_inv =</span> <span class="dv">6</span> <span class="sc">-</span> m4,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ae3_inv =</span> <span class="dv">6</span> <span class="sc">-</span> ae3,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">motivacion =</span> <span class="fu">rowMeans</span>(<span class="fu">pick</span>(m1, m2, m3, m4_inv), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ansiedad =</span> <span class="fu">rowMeans</span>(<span class="fu">pick</span>(a1<span class="sc">:</span>a4), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">autoeficacia =</span> <span class="fu">rowMeans</span>(<span class="fu">pick</span>(ae1, ae2, ae3_inv, ae4), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, motivacion, ansiedad, autoeficacia)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 4
   id    motivacion ansiedad autoeficacia
   &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;
 1 E001        1.75     3.75         2.5 
 2 E002        3.5      4            3.25
 3 E003        2.67     4.25         2   
 4 E004        3.75     4            3   
 5 E005        3.33     2.75         3.75
 6 E006        2.5      3.25         3   
 7 E007        4.5      3.5          3.5 
 8 E008        3.75     3            3   
 9 E009        4        4.33         2.75
10 E010        4.75     4            4.75
# ℹ 310 more rows</code></pre>
</div>
</div>
<p>Guardamos los datos con las nuevas variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(encuesta, <span class="st">"checkpoints/encuesta_escalas.rds"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="resumir-varias-variables-a-la-vez-across" class="level2">
<h2 class="anchored" data-anchor-id="resumir-varias-variables-a-la-vez-across">Resumir varias variables a la vez: <code>across()</code></h2>
<p><code>across()</code> también funciona dentro de <code>summarise()</code>. Cuando la función necesita argumentos (como <code>na.rm = TRUE</code>), se escribe como una función breve con <code>\(x)</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curso) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(motivacion, ansiedad, autoeficacia), \(x) <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  curso  motivacion ansiedad autoeficacia
  &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;
1 1º ESO       3.35     2.98         2.95
2 2º ESO       2.99     3.05         2.96
3 3º ESO       2.98     3.05         2.98
4 4º ESO       2.85     3.18         2.89</code></pre>
</div>
</div>
<p>Con una lista de funciones se calculan varios estadísticos de cada variable. Los nombres de las columnas resultantes combinan el de la variable y el de la función:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ciclo) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(motivacion, ansiedad, autoeficacia),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="at">media =</span> \(x) <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">dt =</span> \(x) <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  ciclo         motivacion_media motivacion_dt ansiedad_media ansiedad_dt
  &lt;chr&gt;                    &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt;
1 Primer ciclo              3.15         0.871           3.02       0.885
2 Segundo ciclo             2.91         0.855           3.11       0.893
# ℹ 2 more variables: autoeficacia_media &lt;dbl&gt;, autoeficacia_dt &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Y <code>where()</code> permite resumir, por ejemplo, todas las variables numéricas:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">round</span>(<span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 19
   edad    m1    m2    m3    m4    a1    a2    a3    a4   ae1   ae2   ae3   ae4
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  14.1  3.05  3.09  3.11   3.1  3.02  3.09  3.12  3.05  2.95  2.95  3.11  2.98
# ℹ 6 more variables: nota &lt;dbl&gt;, m4_inv &lt;dbl&gt;, ae3_inv &lt;dbl&gt;,
#   motivacion &lt;dbl&gt;, ansiedad &lt;dbl&gt;, autoeficacia &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="seleccionar-filas-por-posición-slice_" class="level2">
<h2 class="anchored" data-anchor-id="seleccionar-filas-por-posición-slice_">Seleccionar filas por posición: <code>slice_*()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(nota, <span class="at">n =</span> <span class="dv">3</span>)              <span class="co"># las 3 notas más altas</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 26
  marca_temporal    id    centro curso sexo   edad    m1    m2    m3    m4    a1
  &lt;chr&gt;             &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 05/10/2026 23:43… E013  C07    2º E… Chico    14     3     3     5     2    NA
2 08/10/2026 01:36… E062  C09    3º E… Chica    14     5     4     5     2     2
3 08/10/2026 18:07… E082  C06    3º E… Chica    14     4    NA     5     2     2
4 09/10/2026 02:59… E095  C07    2º E… Chico    14     4     4     4     3     2
5 13/10/2026 23:05… E200  C02    1º E… Chico    12     5     3     5     1     2
6 17/10/2026 12:16… E274  C07    1º E… Chica    13     5     5     4     1     3
7 19/10/2026 01:49… E313  C07    1º E… Chico    12     5     5     5     1     2
# ℹ 15 more variables: a2 &lt;dbl&gt;, a3 &lt;dbl&gt;, a4 &lt;dbl&gt;, ae1 &lt;dbl&gt;, ae2 &lt;dbl&gt;,
#   ae3 &lt;dbl&gt;, ae4 &lt;dbl&gt;, nota &lt;dbl&gt;, ciclo &lt;chr&gt;, calificacion &lt;fct&gt;,
#   m4_inv &lt;dbl&gt;, ae3_inv &lt;dbl&gt;, motivacion &lt;dbl&gt;, ansiedad &lt;dbl&gt;,
#   autoeficacia &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(centro) <span class="sc">|&gt;</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(motivacion, <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span>     <span class="co"># el estudiante menos motivado de cada centro</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(centro, id, motivacion)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 3
# Groups:   centro [10]
   centro id    motivacion
   &lt;fct&gt;  &lt;chr&gt;      &lt;dbl&gt;
 1 C01    E131        1   
 2 C02    E161        1   
 3 C02    E223        1   
 4 C03    E110        1.75
 5 C03    E117        1.75
 6 C04    E112        1.5 
 7 C05    E244        1   
 8 C06    E084        2.25
 9 C07    E037        1.25
10 C07    E060        1.25
11 C07    E229        1.25
12 C08    E309        1   
13 C09    E042        2.25
14 C10    E241        1.5 </code></pre>
</div>
</div>
<p><code>slice_head(n = 5)</code> da las 5 primeras filas, y <code>slice_sample(n = 10)</code> 10 filas al azar.</p>
</section>
<section id="mutate-por-grupos" class="level2">
<h2 class="anchored" data-anchor-id="mutate-por-grupos"><code>mutate()</code> por grupos</h2>
<p>Con <code>group_by()</code>, <code>mutate()</code> hace los cálculos <strong>dentro de cada grupo</strong>, pero mantiene todas las filas. Por ejemplo, para comparar la nota de cada estudiante con la media de su centro:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(centro) <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">media_centro =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dif_centro =</span> nota <span class="sc">-</span> media_centro</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, centro, nota, media_centro, dif_centro)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 5
   id    centro  nota media_centro dif_centro
   &lt;chr&gt; &lt;fct&gt;  &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
 1 E001  C08      5.5         6.01     -0.512
 2 E002  C03      4.1         6.39     -2.29 
 3 E003  C02      7.7         6.16      1.54 
 4 E004  C07      4.8         6.15     -1.35 
 5 E005  C03      7.5         6.39      1.11 
 6 E006  C02      8.1         6.16      1.94 
 7 E007  C01      6.8         6.15      0.653
 8 E008  C04      7.8         6.03      1.77 
 9 E009  C07      6.8         6.15      0.651
10 E010  C03      9.6         6.39      3.21 
# ℹ 310 more rows</code></pre>
</div>
</div>
<p><code>ungroup()</code> quita la agrupación para que las operaciones siguientes se apliquen a toda la tabla.</p>
</section>
</section>
<section id="ejercicio-1" class="level1">
<h1>Ejercicio 1</h1>
<p>Ve a <code>sesion2_ejercicios.qmd</code>, <strong>Ejercicio 1. Un informe por centro</strong> (15 minutos).</p>
</section>
<section id="bloque-2-3" class="level1">
<h1>2.3. Reorganizar y combinar tablas</h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pasar datos de medidas repetidas de formato ancho a largo (y al revés), y unir información que está en tablas distintas.</p>
<p><strong>Punto de control:</strong> <code>encuesta &lt;- readRDS("checkpoints/encuesta_escalas.rds")</code></p>
</div>
</div>
<section id="datos-ordenados-tidy-data" class="level2">
<h2 class="anchored" data-anchor-id="datos-ordenados-tidy-data">Datos ordenados (<em>tidy data</em>)</h2>
<p>Las funciones del <em>tidyverse</em> funcionan mejor con datos <strong>ordenados</strong>:</p>
<ul>
<li>cada variable en una columna,</li>
<li>cada observación en una fila,</li>
<li>cada valor en una celda.</li>
</ul>
<p>Con medidas repetidas, “una observación” puede ser un participante o un participante en un momento. Según el análisis, necesitaremos una forma u otra.</p>
</section>
<section id="de-ancho-a-largo-pivot_longer" class="level2">
<h2 class="anchored" data-anchor-id="de-ancho-a-largo-pivot_longer">De ancho a largo: <code>pivot_longer()</code></h2>
<p>Los datos de la intervención en comprensión lectora tienen una columna para cada momento de medida. Es el formato <strong>ancho</strong>, habitual al introducir datos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>intervencion <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datos/intervencion_prepost.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="fu">factor</span>(grupo, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Intervención"</span>)))</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>intervencion</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 109 × 5
   id    grupo        comprension_pre comprension_post comprension_seguimiento
   &lt;chr&gt; &lt;fct&gt;                  &lt;dbl&gt;            &lt;dbl&gt;                   &lt;dbl&gt;
 1 E003  Control                   44               64                      45
 2 E004  Intervención              42               60                      48
 3 E009  Intervención              50               66                      60
 4 E013  Intervención              57               70                      66
 5 E015  Control                   53               56                      57
 6 E016  Intervención              62               65                      NA
 7 E020  Control                   61               61                      61
 8 E021  Intervención              63               81                      68
 9 E022  Intervención              80               80                      86
10 E024  Control                   60               61                      64
# ℹ 99 more rows</code></pre>
</div>
</div>
<p>Para muchos análisis y para casi todos los gráficos necesitamos el formato <strong>largo</strong>: una fila por participante y momento. La función <code>pivot_longer()</code> “apila” las columnas indicadas:</p>
<ul>
<li><code>cols</code>: las columnas que queremos apilar.</li>
<li><code>names_to</code>: el nombre de la nueva columna que dirá de qué columna venía cada valor.</li>
<li><code>values_to</code>: el nombre de la nueva columna con los valores.</li>
<li><code>names_prefix</code> (opcional): texto que se quita del principio de los nombres.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>intervencion_larga <span class="ot">&lt;-</span> intervencion <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"comprension_"</span>),</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"momento"</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"comprension_"</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"comprension"</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">momento =</span> <span class="fu">factor</span>(momento, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"pre"</span>, <span class="st">"post"</span>, <span class="st">"seguimiento"</span>)))</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>intervencion_larga</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 327 × 4
   id    grupo        momento     comprension
   &lt;chr&gt; &lt;fct&gt;        &lt;fct&gt;             &lt;dbl&gt;
 1 E003  Control      pre                  44
 2 E003  Control      post                 64
 3 E003  Control      seguimiento          45
 4 E004  Intervención pre                  42
 5 E004  Intervención post                 60
 6 E004  Intervención seguimiento          48
 7 E009  Intervención pre                  50
 8 E009  Intervención post                 66
 9 E009  Intervención seguimiento          60
10 E013  Intervención pre                  57
# ℹ 317 more rows</code></pre>
</div>
</div>
<p>109 estudiantes × 3 momentos = 327 filas. Ahora es inmediato resumir por grupo y momento:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>medias_intervencion <span class="ot">&lt;-</span> intervencion_larga <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo, momento) <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">mean</span>(comprension, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>medias_intervencion</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  grupo        momento     media
  &lt;fct&gt;        &lt;fct&gt;       &lt;dbl&gt;
1 Control      pre          51.1
2 Control      post         52.7
3 Control      seguimiento  53.0
4 Intervención pre          51.2
5 Intervención post         58.7
6 Intervención seguimiento  58.1</code></pre>
</div>
</div>
</section>
<section id="de-largo-a-ancho-pivot_wider" class="level2">
<h2 class="anchored" data-anchor-id="de-largo-a-ancho-pivot_wider">De largo a ancho: <code>pivot_wider()</code></h2>
<p>La operación contraria es útil, sobre todo, para presentar resultados: una tabla con los grupos en filas y los momentos en columnas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>medias_intervencion <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> momento, <span class="at">values_from =</span> media)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  grupo          pre  post seguimiento
  &lt;fct&gt;        &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;
1 Control       51.1  52.7        53.0
2 Intervención  51.2  58.7        58.1</code></pre>
</div>
</div>
<p>Otro uso habitual: convertir un recuento en una tabla de doble entrada.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(curso, sexo) <span class="sc">|&gt;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sexo, <span class="at">values_from =</span> n)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  curso  Chica Chico `Prefiero no decirlo`
  &lt;fct&gt;  &lt;int&gt; &lt;int&gt;                 &lt;int&gt;
1 1º ESO    39    34                     5
2 2º ESO    44    47                     4
3 3º ESO    26    41                     3
4 4º ESO    37    40                    NA</code></pre>
</div>
</div>
</section>
<section id="combinar-tablas-joins" class="level2">
<h2 class="anchored" data-anchor-id="combinar-tablas-joins">Combinar tablas: <em>joins</em></h2>
<p>La información de los centros (titularidad, zona) está en otra tabla. Para añadirla a cada estudiante, unimos las tablas por la columna que tienen en común, <code>centro</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>centros <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"datos/centros.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">centro =</span> <span class="fu">factor</span>(centro), <span class="at">titularidad =</span> <span class="fu">factor</span>(titularidad), <span class="at">zona =</span> <span class="fu">factor</span>(zona))</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>encuesta_centros <span class="ot">&lt;-</span> encuesta <span class="sc">|&gt;</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(centros, <span class="at">by =</span> <span class="st">"centro"</span>)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>encuesta_centros <span class="sc">|&gt;</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, centro, titularidad, zona, nota)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 5
   id    centro titularidad zona    nota
   &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt;       &lt;fct&gt;  &lt;dbl&gt;
 1 E001  C08    Concertada  Urbana   5.5
 2 E002  C03    Concertada  Urbana   4.1
 3 E003  C02    Pública     Urbana   7.7
 4 E004  C07    Pública     Urbana   4.8
 5 E005  C03    Concertada  Urbana   7.5
 6 E006  C02    Pública     Urbana   8.1
 7 E007  C01    Pública     Urbana   6.8
 8 E008  C04    Pública     Rural    7.8
 9 E009  C07    Pública     Urbana   6.8
10 E010  C03    Concertada  Urbana   9.6
# ℹ 310 more rows</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Qué filas conserva</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>left_join(x, y)</code></td>
<td>Todas las de <code>x</code>; añade las columnas de <code>y</code> donde hay coincidencia (donde no, <code>NA</code>). La más habitual.</td>
</tr>
<tr class="even">
<td><code>inner_join(x, y)</code></td>
<td>Solo las que tienen coincidencia en ambas tablas.</td>
</tr>
<tr class="odd">
<td><code>full_join(x, y)</code></td>
<td>Todas las de ambas tablas.</td>
</tr>
<tr class="even">
<td><code>anti_join(x, y)</code></td>
<td>Las de <code>x</code> que <strong>no</strong> tienen coincidencia en <code>y</code>. No añade columnas: sirve para detectar problemas.</td>
</tr>
</tbody>
</table>
<p>Por ejemplo, ¿están todos los estudiantes de la intervención en la encuesta? Y, para los que sí están, ¿de qué curso son?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>intervencion <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(encuesta, <span class="at">by =</span> <span class="st">"id"</span>)       <span class="co"># 0 filas: todos están</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 5
# ℹ 5 variables: id &lt;chr&gt;, grupo &lt;fct&gt;, comprension_pre &lt;dbl&gt;,
#   comprension_post &lt;dbl&gt;, comprension_seguimiento &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>intervencion <span class="sc">|&gt;</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(<span class="fu">select</span>(encuesta, id, curso, sexo), <span class="at">by =</span> <span class="st">"id"</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(grupo, curso)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  grupo        curso      n
  &lt;fct&gt;        &lt;fct&gt;  &lt;int&gt;
1 Control      1º ESO    26
2 Control      2º ESO    27
3 Intervención 1º ESO    29
4 Intervención 2º ESO    27</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Especifica siempre la columna de unión con <code>by</code>, y comprueba después que el número de filas es el esperado: si la columna de unión tiene valores repetidos en la segunda tabla, las filas se multiplican.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(encuesta)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 320</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(encuesta_centros)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 320</code></pre>
</div>
</div>
<p>Para <strong>apilar</strong> dos tablas con las mismas columnas (por ejemplo, los datos de dos cursos académicos), se usa <code>bind_rows()</code>.</p>
</section>
</section>
<section id="bloque-2-4" class="level1">
<h1>2.4. Gráficos con <code>ggplot2</code></h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Construir los gráficos más habituales en un artículo y adaptar su aspecto: etiquetas, colores, paneles y temas.</p>
<p><strong>Punto de control:</strong> <code>encuesta &lt;- readRDS("checkpoints/encuesta_escalas.rds")</code></p>
</div>
</div>
<section id="la-gramática-de-los-gráficos" class="level2">
<h2 class="anchored" data-anchor-id="la-gramática-de-los-gráficos">La gramática de los gráficos</h2>
<p><code>ggplot2</code> construye los gráficos por <strong>capas</strong>, que se suman con <code>+</code>:</p>
<ol type="1">
<li><code>ggplot(datos, aes(...))</code>: los <strong>datos</strong> y la <strong>estética</strong> (<code>aes</code>), es decir, qué variable va en cada eje, en el color, etc.</li>
<li><code>geom_*()</code>: la <strong>geometría</strong>, o cómo se representan los datos (puntos, barras, cajas…).</li>
<li>Opcionalmente: etiquetas (<code>labs</code>), escalas (<code>scale_*</code>), paneles (<code>facet_wrap</code>), tema (<code>theme_*</code>)…</li>
</ol>
<p>Construyamos un gráfico capa a capa:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> autoeficacia, <span class="at">y =</span> nota))              <span class="co"># solo los ejes</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> autoeficacia, <span class="at">y =</span> nota)) <span class="sc">+</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()                                                  <span class="co"># + los puntos</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> autoeficacia, <span class="at">y =</span> nota)) <span class="sc">+</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span>                                  <span class="co"># + la recta de regresión</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Autoeficacia académica (1-5)"</span>, <span class="at">y =</span> <span class="st">"Nota media"</span>,</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Autoeficacia y rendimiento"</span>) <span class="sc">+</span>                  <span class="co"># + etiquetas</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()                                               <span class="co"># + un tema</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="asignar-o-fijar-dentro-o-fuera-de-aes" class="level2">
<h2 class="anchored" data-anchor-id="asignar-o-fijar-dentro-o-fuera-de-aes">Asignar o fijar: dentro o fuera de <code>aes()</code></h2>
<p>Una propiedad visual (color, tamaño, forma, transparencia) puede <strong>depender de una variable</strong> o ser <strong>fija</strong> para todo el gráfico:</p>
<ul>
<li>Dentro de <code>aes()</code>: <code>aes(color = sexo)</code> asigna un color a cada valor de la variable y crea una leyenda.</li>
<li>Fuera de <code>aes()</code>: <code>geom_point(color = "steelblue")</code> pinta todos los puntos del mismo color.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sexo <span class="sc">!=</span> <span class="st">"Prefiero no decirlo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> autoeficacia, <span class="at">y =</span> nota, <span class="at">color =</span> sexo)) <span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Autoeficacia académica (1-5)"</span>, <span class="at">y =</span> <span class="st">"Nota media"</span>, <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa que podemos empezar con una cadena de <code>dplyr</code> y pasar el resultado a <code>ggplot()</code> con <code>|&gt;</code>. A partir de ahí, las capas se suman con <code>+</code>. Como el color está en <code>aes()</code> de <code>ggplot()</code>, se aplica a todas las capas: hay una recta para cada grupo.</p>
</section>
<section id="distribución-de-una-variable" class="level2">
<h2 class="anchored" data-anchor-id="distribución-de-una-variable">Distribución de una variable</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> nota)) <span class="sc">+</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Nota"</span>, <span class="at">y =</span> <span class="st">"Número de estudiantes"</span>) <span class="sc">+</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para comparar la distribución en varios grupos, las curvas de densidad superpuestas son más legibles que varios histogramas:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> ansiedad, <span class="at">fill =</span> ciclo)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ansiedad ante los exámenes (1-5)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>, <span class="at">fill =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="comparar-grupos-diagramas-de-caja" class="level2">
<h2 class="anchored" data-anchor-id="comparar-grupos-diagramas-de-caja">Comparar grupos: diagramas de caja</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> curso, <span class="at">y =</span> motivacion)) <span class="sc">+</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Motivación (1-5)"</span>) <span class="sc">+</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>geom_jitter()</code> añade los puntos individuales, con un pequeño desplazamiento horizontal al azar para que no se solapen. Con pocos datos, ver los puntos es más honesto que ver solo la caja. (<code>outlier.shape = NA</code> evita que los atípicos aparezcan dos veces).</p>
</section>
<section id="frecuencias-gráficos-de-barras" class="level2">
<h2 class="anchored" data-anchor-id="frecuencias-gráficos-de-barras">Frecuencias: gráficos de barras</h2>
<p><code>geom_bar()</code> cuenta las filas de cada categoría. Con <code>fill</code>, cada barra se divide según otra variable, y <code>position</code> indica cómo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> curso, <span class="at">fill =</span> calificacion)) <span class="sc">+</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Número de estudiantes"</span>, <span class="at">fill =</span> <span class="st">"Calificación"</span>) <span class="sc">+</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(encuesta, <span class="fu">aes</span>(<span class="at">x =</span> curso, <span class="at">fill =</span> calificacion)) <span class="sc">+</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span>                        <span class="co"># barras una al lado de otra</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Número de estudiantes"</span>, <span class="at">fill =</span> <span class="st">"Calificación"</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(calificacion)) <span class="sc">|&gt;</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> curso, <span class="at">fill =</span> calificacion)) <span class="sc">+</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span>                         <span class="co"># proporciones: cada barra suma 100 %</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdYlGn"</span>) <span class="sc">+</span>              <span class="co"># una paleta de colores</span></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Porcentaje"</span>, <span class="at">fill =</span> <span class="st">"Calificación"</span>) <span class="sc">+</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Si ya tenemos los valores calculados (por ejemplo, con <code>summarise()</code>), se usa <code>geom_col()</code>, que no cuenta sino que dibuja el valor de <code>y</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(centro) <span class="sc">|&gt;</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">aprobados =</span> <span class="fu">mean</span>(nota <span class="sc">&gt;=</span> <span class="dv">5</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(centro, aprobados), <span class="at">y =</span> aprobados)) <span class="sc">+</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span>                                         <span class="co"># barras horizontales</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Porcentaje de aprobados"</span>) <span class="sc">+</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>reorder(centro, aprobados)</code> ordena los centros según su porcentaje de aprobados.</p>
</section>
<section id="paneles-facet_wrap" class="level2">
<h2 class="anchored" data-anchor-id="paneles-facet_wrap">Paneles: <code>facet_wrap()</code></h2>
<p><code>facet_wrap()</code> repite el gráfico para cada valor de una variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>encuesta_centros <span class="sc">|&gt;</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> autoeficacia, <span class="at">y =</span> nota)) <span class="sc">+</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> zona) <span class="sc">+</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Autoeficacia académica (1-5)"</span>, <span class="at">y =</span> <span class="st">"Nota media"</span>) <span class="sc">+</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="medias-por-grupo-y-momento-el-gráfico-de-una-intervención" class="level2">
<h2 class="anchored" data-anchor-id="medias-por-grupo-y-momento-el-gráfico-de-una-intervención">Medias por grupo y momento: el gráfico de una intervención</h2>
<p>Con los datos en formato largo del bloque anterior, <code>stat_summary()</code> calcula y dibuja directamente la media de cada grupo y momento, y su error típico (<code>mean_se</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(intervencion_larga, <span class="fu">aes</span>(<span class="at">x =</span> momento, <span class="at">y =</span> comprension, <span class="at">color =</span> grupo, <span class="at">group =</span> grupo)) <span class="sc">+</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Pre"</span>, <span class="st">"Post"</span>, <span class="st">"Seguimiento"</span>)) <span class="sc">+</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Comprensión lectora (media ± ET)"</span>, <span class="at">color =</span> <span class="st">"Grupo"</span>) <span class="sc">+</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sesion2_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ajustar-el-aspecto" class="level2">
<h2 class="anchored" data-anchor-id="ajustar-el-aspecto">Ajustar el aspecto</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Para cambiar…</th>
<th>Usa…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Títulos de ejes y leyendas</td>
<td><code>labs(x = , y = , color = , fill = , title = )</code></td>
</tr>
<tr class="even">
<td>Colores</td>
<td><code>scale_color_brewer()</code>, <code>scale_fill_brewer()</code>, <code>scale_color_manual(values = c(...))</code></td>
</tr>
<tr class="odd">
<td>Formato de los ejes</td>
<td><code>scale_y_continuous(labels = scales::percent, limits = c(0, 10))</code></td>
</tr>
<tr class="even">
<td>El aspecto general</td>
<td><code>theme_minimal()</code>, <code>theme_bw()</code>, <code>theme_classic()</code></td>
</tr>
<tr class="odd">
<td>Detalles</td>
<td><code>theme(legend.position = "bottom", text = element_text(size = 14))</code></td>
</tr>
</tbody>
</table>
</section>
<section id="guardar-un-gráfico" class="level2">
<h2 class="anchored" data-anchor-id="guardar-un-gráfico">Guardar un gráfico</h2>
<p><code>ggsave()</code> guarda el último gráfico en el formato que indique la extensión (<code>.png</code>, <code>.pdf</code>, <code>.svg</code>…):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"figura_intervencion.png"</span>, <span class="at">width =</span> <span class="dv">16</span>, <span class="at">height =</span> <span class="dv">10</span>, <span class="at">units =</span> <span class="st">"cm"</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>También con RStudio
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la pestaña <em>Plots</em>, <em>Export &gt; Save as Image…</em> guarda el gráfico eligiendo el formato y el tamaño en un cuadro de diálogo. Para un artículo es mejor <code>ggsave()</code>: el tamaño y la resolución quedan escritos en el código y son siempre los mismos.</p>
</div>
</div>
</section>
</section>
<section id="bloque-2-5" class="level1">
<h1>2.5. Primeros análisis</h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ejecutar e interpretar la salida de tres análisis básicos: correlación, prueba <em>t</em> y regresión lineal.</p>
<p><strong>Punto de control:</strong> <code>encuesta &lt;- readRDS("checkpoints/encuesta_escalas.rds")</code></p>
</div>
</div>
<section id="correlación" class="level2">
<h2 class="anchored" data-anchor-id="correlación">Correlación</h2>
<p>La matriz de correlaciones entre varias variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>encuesta <span class="sc">|&gt;</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(motivacion, ansiedad, autoeficacia, nota) <span class="sc">|&gt;</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>) <span class="sc">|&gt;</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             motivacion ansiedad autoeficacia  nota
motivacion         1.00    -0.12         0.41  0.44
ansiedad          -0.12     1.00        -0.33 -0.45
autoeficacia       0.41    -0.33         1.00  0.60
nota               0.44    -0.45         0.60  1.00</code></pre>
</div>
</div>
<p>Para contrastar una correlación concreta, con su intervalo de confianza y valor <em>p</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(encuesta<span class="sc">$</span>autoeficacia, encuesta<span class="sc">$</span>nota)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  encuesta$autoeficacia and encuesta$nota
t = 13.237, df = 312, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.5237583 0.6661466
sample estimates:
     cor 
0.599678 </code></pre>
</div>
</div>
</section>
<section id="prueba-t" class="level2">
<h2 class="anchored" data-anchor-id="prueba-t">Prueba <em>t</em></h2>
<p>¿Difiere la ansiedad ante los exámenes entre chicas y chicos? La sintaxis <code>variable ~ grupo</code> se lee “variable <strong>en función de</strong> grupo”, y es la misma que usan casi todos los modelos en R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>encuesta_2sexos <span class="ot">&lt;-</span> encuesta <span class="sc">|&gt;</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sexo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chica"</span>, <span class="st">"Chico"</span>))</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(ansiedad <span class="sc">~</span> sexo, <span class="at">data =</span> encuesta_2sexos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  ansiedad by sexo
t = 2.0385, df = 297.01, p-value = 0.04238
alternative hypothesis: true difference in means between group Chica and group Chico is not equal to 0
95 percent confidence interval:
 0.007183184 0.407876853
sample estimates:
mean in group Chica mean in group Chico 
            3.16895             2.96142 </code></pre>
</div>
</div>
<ul>
<li>Por defecto, R aplica la corrección de <strong>Welch</strong> (no asume varianzas iguales). Para la prueba <em>t</em> clásica: <code>var.equal = TRUE</code>.</li>
<li><code>mean in group ...</code>: las medias de cada grupo; <code>95 percent confidence interval</code>: el intervalo de la <strong>diferencia</strong> de medias.</li>
</ul>
<p>Para muestras relacionadas (por ejemplo, pre y post en los mismos estudiantes), <code>paired = TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>grupo_intervencion <span class="ot">&lt;-</span> intervencion <span class="sc">|&gt;</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(grupo <span class="sc">==</span> <span class="st">"Intervención"</span>)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(grupo_intervencion<span class="sc">$</span>comprension_post, grupo_intervencion<span class="sc">$</span>comprension_pre, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  grupo_intervencion$comprension_post and grupo_intervencion$comprension_pre
t = 9.3004, df = 55, p-value = 7.02e-13
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 5.855882 9.072689
sample estimates:
mean difference 
       7.464286 </code></pre>
</div>
</div>
</section>
<section id="regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal">Regresión lineal</h2>
<p>La función <code>lm()</code> (<em>linear model</em>) usa la misma sintaxis de fórmula: <code>respuesta ~ predictor1 + predictor2 + ...</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(nota <span class="sc">~</span> autoeficacia <span class="sc">+</span> ansiedad, <span class="at">data =</span> encuesta)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nota ~ autoeficacia + ansiedad, data = encuesta)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3194 -0.8083 -0.0351  0.7757  3.1708 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   4.70288    0.44087  10.667  &lt; 2e-16 ***
autoeficacia  1.02240    0.09213  11.098  &lt; 2e-16 ***
ansiedad     -0.51155    0.08482  -6.031 4.61e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.258 on 311 degrees of freedom
  (6 observations deleted due to missingness)
Multiple R-squared:  0.4267,    Adjusted R-squared:  0.423 
F-statistic: 115.7 on 2 and 311 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Coefficients</strong>: para cada predictor, el coeficiente (<code>Estimate</code>), su error típico y su valor <em>p</em> (<code>Pr(&gt;|t|)</code>). El coeficiente de <code>autoeficacia</code> es el cambio esperado en la nota por cada punto más de autoeficacia, manteniendo constante la ansiedad.</li>
<li><strong>Multiple R-squared</strong>: la proporción de varianza de la nota explicada por el modelo.</li>
</ul>
<p>Los factores se pueden incluir como predictores: R toma el primer nivel como referencia.</p>
</section>
<section id="los-resultados-son-listas" class="level2">
<h2 class="anchored" data-anchor-id="los-resultados-son-listas">Los resultados son listas</h2>
<p>El resultado de <code>cor.test()</code>, <code>t.test()</code> o <code>lm()</code> es una <strong>lista</strong> (sesión 1). Lo que vemos en la consola es solo un resumen; podemos extraer cada elemento con <code>$</code> para usarlo en una tabla o en el texto de un informe:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>prueba <span class="ot">&lt;-</span> <span class="fu">t.test</span>(ansiedad <span class="sc">~</span> sexo, <span class="at">data =</span> encuesta_2sexos)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(prueba)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "statistic"   "parameter"   "p.value"     "conf.int"    "estimate"   
 [6] "null.value"  "stderr"      "alternative" "method"      "data.name"  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>prueba<span class="sc">$</span>p.value</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04238109</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>prueba<span class="sc">$</span>estimate</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean in group Chica mean in group Chico 
            3.16895             2.96142 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) autoeficacia     ansiedad 
   4.7028783    1.0224025   -0.5115498 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta misma lógica de fórmulas es la base de los modelos más avanzados que veréis en otros cursos: modelos mixtos, SEM (con el paquete <code>lavaan</code>) o metaanálisis (con <code>metafor</code>).</p>
</div>
</div>
</section>
</section>
<section id="bloque-2-6" class="level1">
<h1>2.6. Resultados en Quarto y tu propio proyecto con <code>renv</code></h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Objetivo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reunir en un informe Quarto tablas, gráficos y resultados estadísticos, y dejar preparado un proyecto propio y reproducible.</p>
</div>
</div>
<section id="un-informe-con-resultados" class="level2">
<h2 class="anchored" data-anchor-id="un-informe-con-resultados">Un informe con resultados</h2>
<p>Todo lo de esta sesión se puede incluir en un documento Quarto como vimos en la sesión 1:</p>
<ul>
<li>Una tabla de <code>dplyr</code> se muestra con formato con <code>knitr::kable()</code>, con <code>#| label: tbl-...</code> y <code>#| tbl-cap:</code>.</li>
<li>Un gráfico de <code>ggplot2</code> aparece en el informe donde está su bloque, con <code>#| label: fig-...</code> y <code>#| fig-cap:</code>.</li>
<li>Los resultados de las pruebas se escriben en el texto con código, extrayéndolos de la lista:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb115"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>prueba <span class="ot">&lt;-</span> <span class="fu">t.test</span>(ansiedad <span class="sc">~</span> sexo, <span class="at">data =</span> encuesta_2sexos)</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>Las chicas mostraron una ansiedad media de <span class="in">`r round(prueba$estimate[1], 2)`</span>, frente a</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a><span class="in">`r round(prueba$estimate[2], 2)`</span> en los chicos</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>(_t_ = `r round(prueba$statistic, 2)`, _p_ = <span class="in">`r round(prueba$p.value, 3)`</span>).</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Se convierte en: <em>Las chicas mostraron una ansiedad media de 3.17, frente a 2.96 en los chicos (t = 2.04, p = 0.042).</em></p>
<p>Si mañana se corrige un dato, al volver a generar el informe todos los números se actualizan.</p>
</section>
<section id="tu-propio-proyecto-con-renv" class="level2">
<h2 class="anchored" data-anchor-id="tu-propio-proyecto-con-renv">Tu propio proyecto con <code>renv</code></h2>
<p>Para cada análisis nuevo, crea un proyecto con <code>renv</code>. Así, dentro de un año podrás volver a ejecutarlo con las mismas versiones de los paquetes, y cualquier colaborador podrá reproducirlo con <code>renv::restore()</code>.</p>
<ol type="1">
<li><p><em>File &gt; New Project &gt; New Directory &gt; New Project</em>. Elige un nombre y una carpeta, y marca la casilla <em>Use renv with this project</em>. (Si el proyecto ya existe, puedes activar <code>renv</code> en cualquier momento ejecutando <code>renv::init()</code>).</p></li>
<li><p>Crea dentro una carpeta <code>datos/</code> y copia en ella tus ficheros de datos.</p></li>
<li><p>Instala los paquetes que vayas a usar (con <code>install.packages()</code> o desde la pestaña <em>Packages</em>). Se instalan solo en este proyecto:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"psych"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Anota las versiones en <code>renv.lock</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>renv<span class="sc">::</span><span class="fu">snapshot</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Cada vez que instales o actualices un paquete, repite <code>renv::snapshot()</code>. Si tienes dudas de si está al día: <code>renv::status()</code>.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Consejos
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><code>renv</code> guarda una copia de cada versión de cada paquete en una caché compartida, así que instalar el mismo paquete en otro proyecto es casi instantáneo.</li>
<li>Para compartir el proyecto (con un compañero, en un repositorio, como material suplementario de un artículo), incluye <code>renv.lock</code>, <code>.Rprofile</code> y <code>renv/activate.R</code>. <strong>No</strong> hace falta incluir la carpeta <code>renv/library</code>.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="ejercicio-2" class="level1">
<h1>Ejercicio 2</h1>
<p>Ve a <code>sesion2_ejercicios.qmd</code>, <strong>Ejercicio 2. Una pregunta de principio a fin</strong> (15 minutos).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Resumen de la sesión
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Quiero…</th>
<th>Función</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Encadenar operaciones</td>
<td><code>\|&gt;</code> (“y después”)</td>
</tr>
<tr class="even">
<td>Filtrar filas</td>
<td><code>filter()</code>, <code>%in%</code>, <code>!is.na()</code></td>
</tr>
<tr class="odd">
<td>Ordenar</td>
<td><code>arrange()</code>, <code>desc()</code></td>
</tr>
<tr class="even">
<td>Seleccionar, renombrar, reordenar columnas</td>
<td><code>select()</code>, <code>starts_with()</code>, <code>where()</code>, <code>rename()</code>, <code>relocate()</code></td>
</tr>
<tr class="odd">
<td>Crear o recodificar variables</td>
<td><code>mutate()</code>, <code>if_else()</code>, <code>case_when()</code></td>
</tr>
<tr class="even">
<td>La misma operación en varias columnas</td>
<td><code>across()</code></td>
</tr>
<tr class="odd">
<td>Puntuación de una escala</td>
<td><code>rowMeans(pick(...), na.rm = TRUE)</code> (invertir un ítem 1-5: <code>6 - item</code>)</td>
</tr>
<tr class="even">
<td>Contar</td>
<td><code>count()</code></td>
</tr>
<tr class="odd">
<td>Resumir (por grupos)</td>
<td><code>group_by()</code> + <code>summarise()</code>, <code>n()</code></td>
</tr>
<tr class="even">
<td>Filas por posición</td>
<td><code>slice_max()</code>, <code>slice_min()</code>, <code>slice_head()</code></td>
</tr>
<tr class="odd">
<td>De ancho a largo y al revés</td>
<td><code>pivot_longer()</code>, <code>pivot_wider()</code></td>
</tr>
<tr class="even">
<td>Unir tablas</td>
<td><code>left_join(by = ...)</code>, <code>inner_join()</code>, <code>anti_join()</code></td>
</tr>
<tr class="odd">
<td>Gráficos</td>
<td><code>ggplot() + geom_*()</code>, <code>aes()</code>, <code>labs()</code>, <code>scale_*()</code>, <code>facet_wrap()</code>, <code>theme_*()</code>, <code>ggsave()</code></td>
</tr>
<tr class="even">
<td>Correlación</td>
<td><code>cor()</code>, <code>cor.test()</code></td>
</tr>
<tr class="odd">
<td>Prueba <em>t</em></td>
<td><code>t.test(y ~ grupo)</code>, <code>t.test(x, y, paired = TRUE)</code></td>
</tr>
<tr class="even">
<td>Regresión</td>
<td><code>lm(y ~ x1 + x2)</code>, <code>summary()</code>, <code>coef()</code></td>
</tr>
<tr class="odd">
<td>Proyecto reproducible</td>
<td><code>renv::init()</code>, <code>renv::snapshot()</code>, <code>renv::restore()</code></td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="para-seguir-aprendiendo" class="level2">
<h2 class="anchored" data-anchor-id="para-seguir-aprendiendo">Para seguir aprendiendo</h2>
<ul>
<li><em>R para Ciencia de Datos</em> (2ª ed., en español): <a href="https://es.r4ds.hadley.nz" class="uri">https://es.r4ds.hadley.nz</a></li>
<li>Chuletas (<em>cheatsheets</em>) de <code>dplyr</code>, <code>ggplot2</code>, Quarto y otros paquetes: menú <em>Help &gt; Cheat Sheets</em> de RStudio, o <a href="https://posit.co/resources/cheatsheets/" class="uri">https://posit.co/resources/cheatsheets/</a></li>
<li>Guía de Quarto: <a href="https://quarto.org/docs/guide/" class="uri">https://quarto.org/docs/guide/</a></li>
<li>Documentación de <code>renv</code>: <a href="https://rstudio.github.io/renv/" class="uri">https://rstudio.github.io/renv/</a></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/URJCDSLab\.github\.io\/curso-r-uah\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>